### PR TITLE
Code for Fibonacci series

### PR DESCRIPTION
**Pull request by VedantpD**

### CODE REVIEW

**Comment by Midway91** [comment]
@VedantpD Would you like me to wait until the first to merge the request or just do it now?

**Comment by VedantpD** [comment]
@Midway91  I mean I was trying to be in the first 50,000 but it's okay ig , first come first serve.

**Comment by VedantpD** [comment]
@Midway91 Oh wait, it says this repo is not participating in hactoberfest. Please add hactoberfest tag to repo bro

**Comment by 5h0ov** [comment]
yes follow these rules this will help:

image

**Comment by VedantpD** [comment]
@Midway91 Hey thanks, Can you review and accept my PR and add hactoberfest-accepted label

**Comment by Midway91** [comment]
@VedantpD sorry about that

**Pull request merged**
